language: ruby
before_install:
  - sudo apt-get install wget
  - wget http://www.sno.phy.queensu.ca/~phil/exiftool/Image-ExifTool-10.36.tar.gz
  - tar -xzf Image-ExifTool-10.36.tar.gz
  - cd Image-ExifTool-10.36
  - perl Makefile.PL
  - make
  - sudo make install
  - cd ..
  - exiftool -ver
  - gem install contest regtest rim test-unit
rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - ruby-head
  - jruby-19mode
